# Generated by Django 4.1.6 on 2023-02-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post_db", "0002_post_votes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Replies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("reply_test", models.CharField(max_length=800)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                (
                    "parent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="post_db.posts"
                    ),
                ),
            ],
        ),
    ]
