# Generated by Django 4.1.6 on 2023-02-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_db", "0004_posts_no_replies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="replies",
            old_name="reply_test",
            new_name="reply_text",
        ),
    ]
