# Generated by Django 4.1.6 on 2023-02-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_db", "0005_rename_reply_test_replies_reply_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replies",
            name="parent_id",
            field=models.IntegerField(default=0),
        ),
    ]
